import os
# Add ffmpeg to PATH so background threads can find it
os.environ["PATH"] = r"C:\ffmpeg\bin" + os.pathsep + os.environ.get("PATH", "")
print(f"FFmpeg PATH added: {os.environ['PATH'][:100]}")

import threading
from datetime import datetime
from flask import (
    Flask,
    jsonify,
    render_template,
    request,
    send_from_directory,
    session as flask_session,
)
from flask_cors import CORS
from did_service import generate_avatar_video
from cloudinary_service import upload_image
from stt_service import transcribe_audio
from gpt_service import generate_answer
from zoom_service import generate_zoom_signature
from database import db, User, LibraryVideo, Meeting, CustomQA, PrepSession, MeetingSession
from firebase_auth import init_firebase, require_firebase_auth

# Initialize the Flask application
app = Flask(__name__)

# Set secret key so Flask session cookies can be signed.
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev-secret-key")

# Allow React frontend to call Flask API with cookies/session.
# React runs on port 3000, Flask on 5000.
CORS(
    app,
    supports_credentials=True,
    origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
)

# Configure a default local SQLite DB so SQLAlchemy can initialize.
app.config.setdefault(
    "SQLALCHEMY_DATABASE_URI",
    os.getenv("DATABASE_URL", "sqlite:///meeting_proxy.db"),
)
app.config.setdefault("SQLALCHEMY_TRACK_MODIFICATIONS", False)

# Initialize SQLAlchemy with this Flask app.
db.init_app(app)

# Export db so other modules can import from app
# This allows: from app import app, db
from database import db  # noqa - re-export

# Initialize Firebase Admin SDK once when Flask starts.
init_firebase()

# Global dictionary to track meeting prep sessions
# Key: session_id, Value: session data dict
_prep_sessions = {}

# Create database tables if they don't exist
with app.app_context():
    db.create_all()

# Create the temp_audio directory if it doesn't exist
# This is where we temporarily store audio files before transcription
os.makedirs("temp_audio", exist_ok=True)

@app.route('/static/zoom/bundle.js')
def serve_zoom_bundle():
    """
    Serves the bundled Zoom client from the zoom_client/dist directory.
    This file is generated by webpack.
    """
    return send_from_directory(
        os.path.join(os.getcwd(), 'zoom_client', 'dist'),
        'bundle.js'
    )

@app.route('/', methods=['GET'])
def index():
    """
    Renders the main frontend page.
    """
    # Return the HTML template for the index page
    return render_template('index.html')


@app.route("/api/auth/firebase", methods=["POST"])
def firebase_login():
    """
    Called by React frontend after Firebase login.
    Receives Firebase ID token, verifies it, creates
    or gets user in our database, stores in session.
    """
    data = request.get_json() or {}
    id_token = data.get("token")

    if not id_token:
        return jsonify({"error": "No token provided"}), 400

    try:
        from firebase_auth import verify_firebase_token

        decoded = verify_firebase_token(id_token)

        google_id = decoded.get("uid")
        email = decoded.get("email")
        name = decoded.get("name", email)
        picture = decoded.get("picture", "")

        # Get existing user or create a new one on first login.
        user = User.query.filter_by(google_id=google_id).first()

        is_new_user = False
        if not user:
            user = User(
                google_id=google_id,
                email=email,
                name=name,
                profile_picture=picture,
            )
            db.session.add(user)
            db.session.commit()
            user.get_library_folder()
            user.get_cache_folder()
            is_new_user = True
            print(f"[Auth] New user registered: {email}")
        else:
            user.name = name
            user.profile_picture = picture
            db.session.commit()
            print(f"[Auth] User logged in: {email}")

        # Store user ID in server-side session for future API requests.
        flask_session["user_id"] = user.id

        return jsonify(
            {
                "user": user.to_dict(),
                "is_new_user": is_new_user,
                "message": "Login successful!",
            }
        )

    except Exception as e:
        print(f"[Auth] Firebase login error: {e}")
        import traceback
        print(traceback.format_exc())
        return jsonify({"error": str(e)}), 401


@app.route("/api/auth/logout", methods=["POST"])
def logout():
    """Logs out the current user."""
    flask_session.clear()
    return jsonify({"message": "Logged out!"})


@app.route("/api/auth/me", methods=["GET"])
def get_me():
    """
    Returns current logged in user.
    Frontend calls this on page load to check auth status.
    """
    user_id = flask_session.get("user_id")
    if not user_id:
        return jsonify({"user": None}), 200

    user = db.session.get(User, user_id)
    if not user:
        flask_session.clear()
        return jsonify({"user": None}), 200

    return jsonify({"user": user.to_dict()})

@app.route('/generate', methods=['POST'])
def generate():
    """
    Handles the POST request to generate the avatar video.
    Expects 'photo' (file) and 'text' (string) in the request.
    """
    # Get the text from the form data
    text = request.form.get('text')
    
    # Get the file from the request files (named 'photo')
    photo = request.files.get('photo')
    
    # Validate that both required fields are provided
    if not photo or not text:
        return jsonify({"error": "Missing photo file or text"}), 400
        
    try:
        # Step 1: Upload the photo to Cloudinary
        # We pass the file object directly to the service
        print(f"Uploading photo: {photo.filename}")
        image_url = upload_image(photo)
        print(f"Photo uploaded successfully! URL: {image_url}")
        
        # Step 2: Generate the avatar video using D-ID
        # We pass the public Cloudinary URL and the text
        print("Generating video with D-ID...")
        video_url = generate_avatar_video(image_url, text)
        
        # Return the generated video URL and image URL as JSON.
        # image_url is also returned so the frontend can store it in lastImageUrl
        # for the real-time pipeline — D-ID needs it to regenerate avatar videos.
        return jsonify({"video_url": video_url, "image_url": image_url}), 200
        
    except Exception as e:
        # Handle any errors during upload or generation
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/transcribe', methods=['POST'])
def transcribe():
    """
    Handles audio transcription requests.
    Expects an 'audio' file upload.
    Returns the transcribed text.
    """
    # Check if 'audio' file is in the request
    audio_file = request.files.get('audio')
    
    if not audio_file:
        return jsonify({"error": "No audio file provided"}), 400
        
    # Define a temporary path to save the uploaded audio
    # We use the original filename, but you could use a unique ID too
    temp_path = os.path.join("temp_audio", audio_file.filename)
    
    try:
        # Save the file temporarily to disk
        audio_file.save(temp_path)
        print(f"Saved temp audio to: {temp_path}")
        
        # Open the file in binary read mode for OpenAI API
        with open(temp_path, "rb") as audio_file_obj:
            # Call the transcription service
            transcript_text = transcribe_audio(audio_file_obj)
            
        print(f"Transcription result: {transcript_text}")
        
        # Clean up: delete the temporary file
        os.remove(temp_path)
        print(f"Deleted temp file: {temp_path}")
        
        # Return the transcript as JSON
        return jsonify({"transcript": transcript_text}), 200
        
    except Exception as e:
        print(f"Transcription error: {e}")
        # Ensure we clean up the file even if an error occurs
        if os.path.exists(temp_path):
            os.remove(temp_path)
            
        return jsonify({"error": str(e)}), 500

@app.route('/answer', methods=['POST'])
def answer():
    """
    Handles answer generation requests.
    Expects JSON body with 'question' and 'context'.
    Returns the generated answer.
    """
    # Get JSON data from the request
    data = request.get_json()
    
    question = data.get('question')
    context = data.get('context')
    
    # Validate that both required fields are provided
    if not question or not context:
        return jsonify({"error": "Missing question or context"}), 400
        
    try:
        # Call OpenAI GPT-4o-mini to generate the answer
        print("Generating answer using OpenAI GPT-4o-mini...")
        generated_answer = generate_answer(question, context)
        print(f"Generated answer: {generated_answer}")
        
        # Return the answer as JSON
        return jsonify({"answer": generated_answer}), 200
        
    except Exception as e:
        print(f"Answer generation error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/full-pipeline', methods=['POST'])
def full_pipeline():
    """
    Handles the end-to-end pipeline:
    Photo + Context + Question -> Video Answer
    Expects multipart form data: 'photo', 'context', 'question'
    """
    # Get data from the form
    photo = request.files.get('photo')
    context = request.form.get('context')
    question = request.form.get('question')
    
    # Validate all inputs are present
    if not photo or not context or not question:
        return jsonify({"error": "Missing photo, context, or question"}), 400
        
    try:
        # Step 1: Upload photo to Cloudinary
        print(f"Step 1: Uploading photo {photo.filename} to Cloudinary...")
        image_url = upload_image(photo)
        print(f"Photo uploaded! URL: {image_url}")
        
        # Step 2: Generate answer using OpenAI GPT-4o-mini
        print("Step 2: Generating answer from OpenAI GPT-4o-mini...")
        gpt_answer = generate_answer(question, context)
        print(f"Generated answer: {gpt_answer}")
        
        # Step 3: Generate avatar video using D-ID
        print("Step 3: Generating avatar video with D-ID...")
        video_url = generate_avatar_video(image_url, gpt_answer)
        print(f"Video ready! URL: {video_url}")
        
        # Return the final video URL and image URL.
        # image_url lets the frontend pass the Cloudinary URL to the real-time
        # pipeline so D-ID can regenerate the avatar for every new question.
        return jsonify({"video_url": video_url, "image_url": image_url}), 200
        
    except Exception as e:
        print(f"Pipeline error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/zoom-signature', methods=['POST'])
def zoom_signature():
    """
    Generates a Zoom Web SDK signature for the provided meeting number and role.
    Expects JSON body with 'meeting_number' (string) and 'role' (int, 0=attendee).
    Returns the signed signature and sdkKey.
    """
    # Parse JSON body
    data = request.get_json()
    meeting_number = data.get('meeting_number') if data else None
    role = data.get('role') if data else None

    # Validate inputs
    if not meeting_number or role is None:
        return jsonify({"error": "Missing meeting_number or role"}), 400

    try:
        # Generate signature using the Zoom service
        print(f"Generating Zoom signature for meeting {meeting_number} with role {role}")
        signature = generate_zoom_signature(str(meeting_number), int(role))
        sdk_key = os.getenv("ZOOM_SDK_KEY") or ""

        # Return signature and sdkKey to the client
        return jsonify({"signature": signature, "sdkKey": sdk_key}), 200
    except Exception as e:
        print(f"Zoom signature error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/meeting', methods=['GET'])
def meeting_page():
    """
    Renders the Zoom meeting page where the browser joins the meeting.
    """
    # Optionally prefill meeting values from environment if present
    prefill_meeting = os.getenv("MEETING_ID", "")
    prefill_name = os.getenv("DISPLAY_NAME", "Meeting Proxy Bot")
    return render_template('meeting.html', meeting_id=prefill_meeting, display_name=prefill_name)

@app.route('/join-meet', methods=['POST'])
def join_meet_route():
    """
    Starts the Google Meet bot in a background thread so Flask can respond immediately.

    Phase 6 update: now also accepts 'context' and 'image_url' so the real-time
    listener can generate personalised GPT answers and D-ID avatar videos.

    Expected JSON body:
        video_url  (str) : Public URL of the initial D-ID avatar video.
        context    (str) : Free-text bio the user wants GPT to use when answering.
        image_url  (str) : Public Cloudinary URL of the user's photo for D-ID.
    """
    # Read the JSON request body safely and fall back to an empty dict when missing.
    data = request.get_json() or {}

    # Pull the generated avatar video URL from the request body.
    video_url = data.get('video_url')

    # Pull the user context and image URL — both default to empty string if missing.
    # The pipeline will still run without them, but the GPT answers will be generic.
    context   = data.get('context', '')
    image_url = data.get('image_url', '')

    # Validate that the frontend actually sent a usable video URL.
    if not video_url:
        return jsonify({"error": "video_url is required"}), 400

    try:
        # Import the Meet bot only when needed so the normal app startup stays lightweight.
        from meet_bot import run_meet_bot

        # Define a wrapper that passes all three arguments to the bot.
        def run_in_background():
            try:
                print("=== BOT STARTING ===")
                print(f"video_url: {video_url[:50]}")
                print(f"image_url: {image_url[:50]}")
                print(f"context: {context[:50]}")
                
                # run_meet_bot now receives context and image_url so the real-time
                # pipeline can generate personalised avatar responses.
                result = run_meet_bot(video_url, context, image_url)
                
                # Print the bot result so repeated clicks are easier to debug.
                print(f"=== BOT RESULT: {result} ===")
            except Exception as e:
                import traceback
                print(f"=== BOT CRASHED ===")
                print(traceback.format_exc())

        # Create a background thread so Selenium can run without freezing Flask.
        thread = threading.Thread(target=run_in_background)

        # Mark the thread as daemon so it will not block app shutdown.
        thread.daemon = True

        # Start the automation thread right away.
        thread.start()

        # Return immediately so the browser gets a quick response.
        return jsonify({
            "message": "Bot joining meeting and listening for questions in real-time!"
        }), 200
    except Exception as e:
        # Return a server error if the thread setup fails.
        return jsonify({"error": str(e)}), 500


@app.route('/stop-bot', methods=['POST'])
def stop_bot():
    """
    Gracefully stops the real-time bot:
    1. Stops the VAD microphone listener thread.
    2. Closes the Chrome window controlled by Selenium.

    Call this from the frontend "Stop Bot" button.
    """
    try:
        # Import stop_listening here so it is only loaded when needed.
        from realtime_listener import stop_listening

        # Signal the VAD loop to exit on the next iteration.
        stop_listening()
        print("[StopBot] Listener stopped.")

        # Import the global driver reference from meet_bot.
        import meet_bot

        # Close the Chrome browser if a session is currently open.
        if meet_bot._driver is not None:
            try:
                meet_bot._driver.quit()
                print("[StopBot] Chrome closed.")
            except Exception as e:
                # Log the error but don't crash — the browser may already be gone.
                print(f"[StopBot] Error closing Chrome: {e}")
            # Clear the reference so future calls don't try to close a dead driver.
            meet_bot._driver = None

        return jsonify({"message": "Bot stopped!"}), 200

    except Exception as e:
        print(f"[StopBot] Unexpected error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/pregenerate', methods=['POST'])
def pregenerate():
    """
    Manually trigger pre-generation of response library.
    Useful for preparing before a meeting.
    """
    data = request.get_json() or {}
    image_url = data.get('image_url', '')
    context = data.get('context', '')
    name = data.get('name', 'Rafeh')

    if not image_url or not context:
        return jsonify({"error": "image_url and context required"}), 400

    def run_pregenerate():
        from response_library import pregenerate_library
        pregenerate_library(image_url, context, name, voice_id=(user.voice_id if user.voice_provider == 'elevenlabs' else None))

    thread = threading.Thread(target=run_pregenerate, daemon=True)
    thread.start()

    return jsonify({
        "message": "Pre-generating 10 response videos in background!"
    })

@app.route('/favicon.ico')
def favicon():
    """
    Dummy route for favicon to avoid 404 in browser console.
    """
    return '', 204

@app.route('/library-video/<filename>')
def serve_library_video(filename):
    """
    Serves video files for OBS browser source.
    Checks response_library first, then active
    session folders, then all user session folders.
    """
    import re
    from flask import Response
    import mimetypes

    # Sanitize filename to prevent path traversal
    safe_filename = re.sub(r'[^a-zA-Z0-9_\-\.]', '', filename)

    def stream_video(file_path):
        """Stream video with range request support."""
        file_size = os.path.getsize(file_path)
        range_header = request.headers.get('Range', None)

        if range_header:
            # Parse range request (e.g. "bytes=0-")
            byte_start = 0
            byte_end = file_size - 1

            match = re.search(
                r'bytes=(\d+)-(\d*)', range_header
            )
            if match:
                byte_start = int(match.group(1))
                if match.group(2):
                    byte_end = int(match.group(2))

            length = byte_end - byte_start + 1

            with open(file_path, 'rb') as f:
                f.seek(byte_start)
                data = f.read(length)

            response = Response(
                data,
                206,
                mimetype='video/mp4',
                direct_passthrough=True
            )
            response.headers['Content-Range'] = (
                f'bytes {byte_start}-{byte_end}/{file_size}'
            )
            response.headers['Accept-Ranges'] = 'bytes'
            response.headers['Content-Length'] = length
            return response
        else:
            return send_from_directory(
                os.path.dirname(file_path),
                os.path.basename(file_path),
                mimetype='video/mp4'
            )

    # --- SEARCH ORDER ---

    # 1. Check response_library (default)
    library_path = os.path.join(
        os.getcwd(), 'response_library', safe_filename
    )
    if os.path.exists(library_path):
        print(f"[Route] Serving from library: {safe_filename}")
        return stream_video(library_path)

    # 2. Check active session folders in memory
    for session_id, sess in _prep_sessions.items():
        session_folder = sess.get('session_folder', '')
        if session_folder:
            session_path = os.path.join(
                session_folder, safe_filename
            )
            if os.path.exists(session_path):
                print(
                    f"[Route] Serving from session "
                    f"{session_id}: {safe_filename}"
                )
                return stream_video(session_path)

    # 3. Search all user session folders on disk
    users_folder = os.path.join(os.getcwd(), 'users')
    if os.path.exists(users_folder):
        for user_id_dir in os.listdir(users_folder):
            sessions_dir = os.path.join(
                users_folder, user_id_dir, 'sessions'
            )
            if not os.path.exists(sessions_dir):
                continue
            for session_dir in os.listdir(sessions_dir):
                file_path = os.path.join(
                    sessions_dir, session_dir, safe_filename
                )
                if os.path.exists(file_path):
                    print(
                        f"[Route] Serving from disk session "
                        f"{session_dir}: {safe_filename}"
                    )
                    return stream_video(file_path)

    # 4. Check user library folders
    if os.path.exists(users_folder):
        for user_id_dir in os.listdir(users_folder):
            library_dir = os.path.join(
                users_folder, user_id_dir, 'library'
            )
            if os.path.exists(library_dir):
                file_path = os.path.join(
                    library_dir, safe_filename
                )
                if os.path.exists(file_path):
                    print(
                        f"[Route] Serving from user library: "
                        f"{safe_filename}"
                    )
                    return stream_video(file_path)

    # Not found anywhere
    print(f"[Route] ❌ File not found: {safe_filename}")
    return jsonify({'error': 'Video not found'}), 404

@app.route('/avatar-video')
def serve_avatar_video():
    """Serves the current avatar video."""
    from flask import send_from_directory
    folder = os.path.dirname(os.path.abspath(__file__))
    filename = 'avatar_video.mp4'
    full_path = os.path.join(folder, filename)
    if not os.path.exists(full_path):
        print(f"[Route] avatar_video.mp4 not found!")
        return "No video", 404
    return send_from_directory(folder, filename,
                               mimetype='video/mp4')

@app.route('/avatar-player')
def avatar_player():
    """Serves the avatar video player HTML page."""
    from flask import send_from_directory
    folder = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), 'static'
    )
    return send_from_directory(folder, 'avatar_player.html')

@app.route('/idle-player')
def idle_player():
    """Serves the idle photo HTML page."""
    from flask import send_from_directory
    folder = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), 'static'
    )
    return send_from_directory(folder, 'idle_player.html')

@app.route("/api/upload-photo", methods=["POST"])
@require_firebase_auth
def upload_photo():
    """Uploads a photo to Cloudinary and updates user profile."""
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    
    photo = request.files.get("photo")
    if not photo:
        return jsonify({"error": "No photo provided"}), 400
        
    try:
        url = upload_image(photo)
        user.photo_url = url
        db.session.commit()
        return jsonify({"user": user.to_dict()})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/profile", methods=["PUT"])
@require_firebase_auth
def update_profile():
    """Updates user context and meeting link."""
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    
    data = request.get_json() or {}
    # Update the user profile
    if "context" in data:
        user.context = data["context"]
    if "meet_link" in data:
        user.meet_link = data["meet_link"]
    
    # Also support saving voice settings here
    voice_id = data.get('voice_id')
    voice_name = data.get('voice_name')
    if voice_id is not None:
        user.voice_id = voice_id
        user.voice_name = voice_name
        
    db.session.commit()

    return jsonify({"message": "Profile updated", "user": user.to_dict()})

# ==========================================
# ElevenLabs Custom Voice API Routes
# ==========================================

@app.route('/api/voices', methods=['GET'])
@require_firebase_auth
def list_voices():
    """Lists all available ElevenLabs voices."""
    try:
        from elevenlabs_service import list_voices
        voices = list_voices()
        return jsonify({"voices": voices})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/voices/clone', methods=['POST'])
@require_firebase_auth
def clone_voice():
    """Clones a voice using provided audio files."""
    if 'file' not in request.files:
        return jsonify({"error": "No audio file provided"}), 400
        
    name = request.form.get('name', 'Custom Voice')
    files = request.files.getlist('file')
    
    try:
        import tempfile
        from elevenlabs_service import clone_voice
        
        temp_paths = []
        for file in files:
            temp_path = os.path.join("temp_audio", f"sample_{file.filename}")
            file.save(temp_path)
            temp_paths.append(temp_path)
            
        result = clone_voice(name, temp_paths)
        
        # Cleanup
        for path in temp_paths:
            if os.path.exists(path):
                os.remove(path)
                
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/voices/<voice_id>', methods=['DELETE'])
@require_firebase_auth
def delete_voice(voice_id):
    """Deletes a cloned ElevenLabs voice."""
    try:
        from elevenlabs_service import delete_voice
        delete_voice(voice_id)
        
        # If user had this voice selected, clear it
        user_id = flask_session.get('user_id')
        user = db.session.get(User, user_id)
        if user.voice_id == voice_id:
            user.voice_id = None
            user.voice_name = None
            db.session.commit()
            
        return jsonify({"message": "Voice deleted"})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/voices/preview', methods=['POST'])
@require_firebase_auth
def preview_voice():
    """Generates a short audio preview of a voice."""
    data = request.get_json() or {}
    voice_id = data.get('voice_id')
    text = data.get('text')
    
    if not voice_id:
        return jsonify({"error": "voice_id required"}), 400
        
    try:
        from elevenlabs_service import preview_voice
        import base64
        
        audio_path = preview_voice(voice_id, text)
        
        # Read the file and encode as base64 to send to frontend
        with open(audio_path, "rb") as f:
            audio_data = f.read()
            
        b64_audio = base64.b64encode(audio_data).decode('utf-8')
        data_uri = f"data:audio/mp3;base64,{b64_audio}"
        
        # Cleanup
        if os.path.exists(audio_path):
            os.remove(audio_path)
            
        return jsonify({"audio_url": data_uri})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/voice-settings', methods=['PUT'])
@require_firebase_auth
def save_voice_settings():
    """Saves the user's preferred ElevenLabs voice."""
    data = request.get_json() or {}
    voice_id = data.get('voice_id')
    voice_name = data.get('voice_name')
    
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)
    
    # If voice_id is empty string or None, clear it (fallback to Microsoft)
    if not voice_id:
        user.voice_id = None
        user.voice_name = None
    else:
        user.voice_id = voice_id
        user.voice_name = voice_name
        
    db.session.commit()
    return jsonify({
        "message": "Voice settings saved",
        "user": user.to_dict()
    })

@app.route("/api/custom-qa", methods=["GET", "POST"])
@require_firebase_auth
def handle_custom_qa():
    """Manages custom Q&A pairs."""
    user_id = flask_session.get("user_id")
    
    if request.method == "POST":
        data = request.get_json() or {}
        question = data.get("question")
        answer = data.get("answer")
        
        if not question or not answer:
            return jsonify({"error": "Question and answer required"}), 400
            
        item = CustomQA(user_id=user_id, question=question, answer=answer)
        db.session.add(item)
        db.session.commit()
        return jsonify({"item": item.to_dict()})
        
    items = CustomQA.query.filter_by(user_id=user_id).all()
    return jsonify({"items": [i.to_dict() for i in items]})

@app.route("/api/custom-qa/<int:id>", methods=["DELETE"])
@require_firebase_auth
def delete_custom_qa(id):
    """Deletes a custom Q&A pair."""
    user_id = flask_session.get("user_id")
    item = CustomQA.query.filter_by(id=id, user_id=user_id).first()
    if not item:
        return jsonify({"error": "Not found"}), 404
        
    db.session.delete(item)
    db.session.commit()
    return jsonify({"message": "Deleted"})

@app.route("/api/library", methods=["GET", "DELETE"])
@require_firebase_auth
def handle_library():
    """Manages the avatar library."""
    user_id = flask_session.get("user_id")
    
    if request.method == "DELETE":
        LibraryVideo.query.filter_by(user_id=user_id).delete()
        db.session.commit()
        return jsonify({"message": "Library cleared"})
        
    items = LibraryVideo.query.filter_by(user_id=user_id).all()
    # Combine with custom QA items that have videos
    custom_items = CustomQA.query.filter_by(user_id=user_id).all()
    
    all_items = [i.to_dict() for i in items] + [i.to_dict() for i in custom_items if i.video_path]
    return jsonify({"items": all_items})

@app.route("/api/library/generate", methods=["POST"])
@require_firebase_auth
def generate_library():
    """Starts background generation of library videos."""
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    
    if not user.photo_url or not user.context:
        return jsonify({"error": "Photo and context required"}), 400

    # Extract user data before the thread starts so the SQLAlchemy
    # model instance is not accessed from the background thread.
    user_photo_url = user.photo_url or ''
    user_context = user.context or ''
    user_name = user.name or ''
        
    # In a real app, this would use a task queue like Celery.
    # For now, we'll use a background thread as in the existing 'pregenerate' route.
    def run_gen():
        from response_library import pregenerate_library
        pregenerate_library(user_photo_url, user_context, user_name, voice_id=(user.voice_id if user.voice_provider == 'elevenlabs' else None))
        
    threading.Thread(target=run_gen, daemon=True).start()
    return jsonify({"message": "Generation started"})

@app.route("/api/meetings", methods=["GET"])
@require_firebase_auth
def get_meetings():
    """Returns meeting history."""
    user_id = flask_session.get("user_id")
    meetings = Meeting.query.filter_by(user_id=user_id).order_by(Meeting.created_at.desc()).all()
    return jsonify({"items": [m.to_dict() for m in meetings]})

@app.route("/api/meetings/join", methods=["POST"])
@require_firebase_auth
def join_meeting():
    """Joins a meeting as the avatar bot."""
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    
    data = request.get_json() or {}
    meet_link = data.get("meet_link") or user.meet_link
    session_id = data.get("session_id")
    
    if not meet_link:
        return jsonify({"error": "Meeting link required"}), 400
        
    # Create meeting record
    meeting = Meeting(user_id=user_id, meet_link=meet_link, status="active", started_at=datetime.utcnow())
    db.session.add(meeting)
    db.session.commit()

    # Extract user data before the background thread starts.
    user_context = user.context or ''
    user_photo_url = user.photo_url or ''
    user_id_val = user_id
    user_meet_link = user.meet_link or ''

    # Start bot in background
    from meet_bot import run_meet_bot
    def run_bot():
        # Use copied values instead of the detached user instance.
        run_meet_bot(
            video_url="",
            context=user_context,
            image_url=user_photo_url,
            user_id=user_id_val,
            meet_link=meet_link or user_meet_link,
            session_id=session_id,
            voice_id=user.voice_id
        )
        
    threading.Thread(target=run_bot, daemon=True).start()
    
    return jsonify({"meeting": meeting.to_dict()})


@app.route('/api/generate-answer-preview', methods=['POST'])
@require_firebase_auth
def generate_answer_preview():
    """
    Generates an answer preview for a single question
    using OpenAI GPT-4o-mini and the user's context.
    """
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)
    data = request.get_json()
    question = data.get('question')

    if not question:
        return jsonify({'error': 'Question required'}), 400
    if not user.context:
        return jsonify({
            'error': 'Add your context first '
                     'in Profile Settings'
        }), 400

    try:
        from gpt_service import generate_answer
        answer = generate_answer(question, user.context)
        return jsonify({'answer': answer})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/auto-generate-qa', methods=['POST'])
@require_firebase_auth
def auto_generate_qa():
    """
    Auto-generates 10 Q&A pairs using OpenAI GPT-4o-mini
    based on the user's context.
    """
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)

    if not user.context:
        return jsonify(
            {'error': 'Add your context first'}
        ), 400
    if not user.photo_url:
        return jsonify(
            {'error': 'Upload your photo first'}
        ), 400

    try:
        from openai import OpenAI
        import json
        import os

        openai_client = OpenAI(
            api_key=os.getenv('OPENAI_API_KEY')
        )

        prompt = f"""Based on this person's context,
generate exactly 10 questions that would be asked
in a professional meeting or interview.
For each question also provide a natural answer
based on the context.

Context: {user.context}

Return ONLY a valid JSON array, no other text:
[{{"question": "...", "answer": "..."}}, ...]"""

        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2000,
            temperature=0.7
        )

        qa_text = response.choices[0].message.content
        qa_text = qa_text.replace('```json', '').replace('```', '').strip()
        qa_pairs = json.loads(qa_text)

        def generate_in_background():
            with app.app_context():
                u = db.session.get(User, user_id)
                for qa in qa_pairs:
                    try:
                        from user_service import add_custom_qa
                        add_custom_qa(
                            u,
                            qa['question'],
                            qa['answer']
                        )
                        import time
                        time.sleep(2)
                    except Exception as e:
                        print(f"[AutoQA] {e}")

        t = threading.Thread(
            target=generate_in_background,
            daemon=True
        )
        t.start()

        return jsonify({
            'count': len(qa_pairs),
            'message': f'Generating {len(qa_pairs)} videos!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/meeting-prep/suggest-questions',
           methods=['POST'])
@require_firebase_auth
def suggest_questions():
    """
    Uses OpenAI GPT-4o-mini to suggest 18 questions based on
    meeting context and user background.
    """
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)
    data = request.get_json() or {}
    meeting_context = data.get('meeting_context', '')

    if not meeting_context:
        return jsonify(
            {'error': 'Meeting context required'}
        ), 400

    try:
        from openai import OpenAI
        import json
        import os

        openai_client = OpenAI(
            api_key=os.getenv('OPENAI_API_KEY')
        )

        prompt = f"""You are helping prepare someone
for a meeting.

Their personal background:
{user.context or 'Not provided'}

Meeting context:
{meeting_context}

Generate 18 specific questions very likely to be asked
in this meeting. Make them relevant to both the person's
background and the meeting context.

Return ONLY a JSON array of question strings:
["question 1", "question 2", ...]

No other text, just the JSON array."""

        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1000,
            temperature=0.7
        )

        questions_text = response.choices[0].message.content
        questions_text = questions_text.replace(
            '```json', ''
        ).replace('```', '').strip()
        questions = json.loads(questions_text)

        return jsonify({'questions': questions[:18]})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/meeting-prep/generate-answers',
           methods=['POST'])
@require_firebase_auth
def generate_meeting_answers():
    """
    Generates answers for 5 selected questions
    using OpenAI GPT-4o-mini with user + meeting context.
    """
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)
    data = request.get_json() or {}
    questions = data.get('questions', [])
    meeting_context = data.get('meeting_context', '')

    if len(questions) != 5:
        return jsonify(
            {'error': '5 questions required'}
        ), 400

    try:
        from gpt_service import generate_answer

        qa_list = []
        for q in questions:
            combined_context = f"""
Personal background: {user.context or ''}
Meeting context: {meeting_context}
            """
            answer = generate_answer(q, combined_context)
            qa_list.append({
                'question': q,
                'answer': answer
            })

        return jsonify({'qa_list': qa_list})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/meeting-prep/generate-videos', methods=['POST'])
@require_firebase_auth
def generate_prep_videos():
    global _prep_sessions
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    data = request.get_json() or {}
    qa_list = data.get("qa_list")
    meet_link = data.get("meet_link")
    meeting_context = data.get("meeting_context")
    
    if not qa_list or not meeting_context:
        return jsonify({"error": "QA list and meeting context required"}), 400
    
    if not user.photo_url:
        return jsonify(
            {'error': 'Upload photo first'}
        ), 400

    import uuid
    import json
    session_id = str(uuid.uuid4())[:8]

    session_folder = os.path.join(
        os.getcwd(), 'users', str(user_id),
        'sessions', session_id
    )
    os.makedirs(session_folder, exist_ok=True)

    # Save session to database immediately
    meeting_session = MeetingSession(
        user_id=user_id,
        session_id=session_id,
        meeting_context=meeting_context,
        qa_pairs=json.dumps(qa_list),
        session_folder=session_folder,
        status='generating',
        videos_total=len(qa_list) + 1
    )
    db.session.add(meeting_session)
    db.session.commit()
    session_db_id = meeting_session.id

    # Also save meet_link to user profile if provided
    if meet_link and not user.meet_link:
        user.meet_link = meet_link
        db.session.commit()

    # Initialize in-memory tracking
    _prep_sessions[session_id] = {
        'user_id': user_id,
        'meet_link': meet_link,
        'qa_list': qa_list,
        'videos': {},
        'progress': 0,
        'status_messages': [],
        'complete': False,
        'error': None,
        'session_folder': session_folder,
        'session_db_id': session_db_id
    }

    def generate_all_videos():
        sess = _prep_sessions[session_id]
        total = len(qa_list) + 1
        completed = 0
        videos_ready = 0

        try:
            from did_service import generate_avatar_video
            from video_utils import download_video
            import time

            for i, qa in enumerate(qa_list):
                sess['status_messages'].append(
                    f"Generating video {i+1}/{len(qa_list)}: "
                    f"{qa['question'][:40]}..."
                )

                try:
                    vid_voice_id = user.voice_id if user.voice_provider == "elevenlabs" else None
                    video_url = generate_avatar_video(
                        user.photo_url, qa['answer'], voice_id=vid_voice_id
                    )
                    safe_name = f"q{i+1}.mp4"
                    video_path = os.path.join(
                        session_folder, safe_name
                    )
                    download_video(video_url, video_path)
                    sess['videos'][qa['question']] = video_path
                    videos_ready += 1
                    sess['status_messages'].append(
                        f"✅ Video {i+1} ready!"
                    )
                except Exception as e:
                    sess['status_messages'].append(
                        f"❌ Video {i+1} failed: {str(e)[:40]}"
                    )

                completed += 1
                sess['progress'] = int(completed / total * 100)

                # Update database progress
                with app.app_context():
                    ms = db.session.get(MeetingSession, session_db_id)
                    if ms:
                        ms.videos_ready = videos_ready
                        db.session.commit()

                time.sleep(2)

            # Generate idle video with minimal text
            # Use a single period for minimal animation
            sess['status_messages'].append(
                "Generating idle nodding video..."
            )
            try:
                # Try to use existing nodding video first
                existing_idle_paths = [
                    os.path.join(
                        os.getcwd(),
                        'response_library',
                        'nodding_idle.mp4'
                    ),
                    os.path.join(
                        os.getcwd(),
                        'response_library',
                        'idle_nodding.mp4'
                    ),
                ]

                existing_idle = None
                for p in existing_idle_paths:
                    if os.path.exists(p):
                        existing_idle = p
                        break

                if existing_idle:
                    # Reuse existing idle video — saves credit
                    import shutil
                    nodding_path = os.path.join(
                        session_folder, "nodding_idle.mp4"
                    )
                    shutil.copy2(existing_idle, nodding_path)
                    sess['videos']['__idle__'] = nodding_path
                    videos_ready += 1
                    sess['status_messages'].append(
                        "✅ Idle video ready (reused)!"
                    )
                    print("[Videos] Reused existing idle video")
                else:
                    # Generate new idle — use minimal text
                    nodding_url = generate_avatar_video(
                        user.photo_url,
                        ".",
                        voice_id=None
                    )
                    nodding_path = os.path.join(
                        session_folder, "nodding_idle.mp4"
                    )
                    download_video(nodding_url, nodding_path)
                    sess['videos']['__idle__'] = nodding_path
                    videos_ready += 1
                    sess['status_messages'].append(
                        "✅ Idle video generated!"
                    )
                    print("[Videos] Generated new idle video")

            except Exception as e:
                sess['status_messages'].append(
                    f"⚠️ Idle video failed: {str(e)[:40]}"
                )
                print(f"[Videos] Idle video error: {e}")

            completed += 1
            sess['progress'] = 100
            sess['complete'] = True
            sess['status_messages'].append(
                "🎉 All videos ready!"
            )

            # Update database — mark session as ready
            with app.app_context():
                ms = db.session.get(MeetingSession, session_db_id)
                if ms:
                    ms.status = 'ready'
                    ms.videos_ready = videos_ready
                    db.session.commit()

        except Exception as e:
            sess['error'] = str(e)
            sess['complete'] = True
            with app.app_context():
                ms = db.session.get(MeetingSession, session_db_id)
                if ms:
                    ms.status = 'failed'
                    db.session.commit()

    t = threading.Thread(
        target=generate_all_videos, daemon=True
    )
    t.start()

    return jsonify({
        'session_id': session_id,
        'message': 'Video generation started!'
    })

@app.route("/api/meeting-prep/status/<session_id>", methods=["GET"])
@require_firebase_auth
def get_prep_status(session_id):
    user_id = flask_session.get("user_id")
    
    # 1. Check in-memory _prep_sessions first (for active generation)
    if session_id in _prep_sessions:
        sess = _prep_sessions[session_id]
        return jsonify({
            'progress': sess['progress'],
            'status_messages': sess['status_messages'],
            'complete': sess['complete'],
            'error': sess['error']
        })
        
    # 2. Fall back to database lookup (for past or reloaded sessions)
    session_record = MeetingSession.query.filter_by(session_id=session_id, user_id=user_id).first()
    if session_record:
        progress = 100 if session_record.status == 'ready' else int((session_record.videos_ready / session_record.videos_total) * 100) if session_record.videos_total else 0
        return jsonify({
            'progress': progress,
            'status_messages': [f"Videos ready: {session_record.videos_ready}/{session_record.videos_total}", f"Status: {session_record.status}"],
            'complete': session_record.status == 'ready',
            'error': session_record.status == 'failed'
        })
        
    # 3. Fall back to checking PrepSession by integer ID just in case
    try:
        session_id_int = int(session_id)
        prep_record = PrepSession.query.filter_by(id=session_id_int, user_id=user_id).first()
        if prep_record:
            return jsonify(prep_record.to_dict())
    except ValueError:
        pass

    return jsonify({"error": "Session not found"}), 404

@app.route("/api/meeting-prep/join/<int:session_id>", methods=["POST"])
@require_firebase_auth
def join_prep_meeting(session_id):
    """
    Final step of prep flow. Joins meeting with session videos.
    """
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    session_record = PrepSession.query.filter_by(id=session_id, user_id=user_id).first()
    
    if not session_record or not session_record.complete:
        return jsonify({"error": "Session not ready or not found"}), 400
        
    meet_link = session_record.meet_link or user.meet_link
    if not meet_link:
        return jsonify({"error": "Meeting link required"}), 400
        
    # Create meeting record
    meeting = Meeting(user_id=user_id, meet_link=meet_link, status="active", started_at=datetime.utcnow())
    db.session.add(meeting)
    db.session.commit()
    
    # Extract session videos from qa_data
    import json
    qa_list = json.loads(session_record.qa_data)
    session_videos = { qa['question'].lower().strip(): qa['video_path'] for qa in qa_list }
    
    # Add idle video
    session_folder = os.path.join(os.getcwd(), "users", str(user_id), "sessions", str(session_id))
    idle_path = os.path.join(session_folder, "idle.mp4")
    if os.path.exists(idle_path):
        session_videos['__idle__'] = idle_path

    # Extract user data before the background thread starts.
    user_context = user.context or ''
    user_photo_url = user.photo_url or ''
    user_id_val = user_id

    # Start bot in background
    from meet_bot import run_meet_bot
    def run_bot():
        with app.app_context():
            run_meet_bot(
                video_url='use_library',
                context=user_context,
                image_url=user_photo_url,
                user_id=user_id_val,
                meet_link=meet_link,
                session_videos=session_videos,
                voice_id=user.voice_id
            )
        
    threading.Thread(target=run_bot, daemon=True).start()
    
    return jsonify({"meeting": meeting.to_dict()})

@app.route('/api/meeting-prep/join/<session_id>',
           methods=['POST'])
@require_firebase_auth
def join_prep_meeting_string(session_id):
    """
    Starts the meeting bot using session-specific videos.
    Accepts meet_link from request body.
    This route handles reusing past meeting sessions.
    """
    # This is a global variable that stores session data in memory
    # It's like a temporary storage for active sessions
    global _prep_sessions
    
    # Get the current user's ID from the session
    user_id = flask_session.get('user_id')
    
    # Find the user in the database
    user = db.session.get(User, user_id)
    
    # Get the data sent in the POST request (JSON format)
    data = request.get_json() or {}

    # Try to get the meeting link from multiple places:
    # 1. From the request data (what the user just entered)
    # 2. From the session in memory (if it was stored before)
    # 3. From the user's profile (saved preference)
    meet_link = (
        data.get('meet_link') or
        _prep_sessions.get(session_id, {}).get('meet_link') or
        user.meet_link
    )

    # If we still don't have a meeting link, we can't proceed
    if not meet_link:
        return jsonify(
            {'error': 'No meeting link provided'}
        ), 400

    # Check if this session is already loaded in memory
    if session_id not in _prep_sessions:
        # If not in memory, try to load it from the database
        # This happens when reusing a past session
        meeting_session = MeetingSession.query.filter_by(
            session_id=session_id,
            user_id=user_id
        ).first()

        # If the session doesn't exist in the database, error
        if not meeting_session:
            return jsonify(
                {'error': 'Session not found'}
            ), 404

        # Parse the Q&A data from the database (it's stored as JSON text)
        import json
        qa_list = json.loads(
            meeting_session.qa_pairs or '[]'
        )
        
        # Get the folder where the videos are stored
        session_folder = meeting_session.session_folder

        # Rebuild the videos dictionary from files on disk
        # Each Q&A has a corresponding video file
        videos = {}
        for i, qa in enumerate(qa_list):
            # Video files are named q1.mp4, q2.mp4, etc.
            video_path = os.path.join(
                session_folder, f"q{i+1}.mp4"
            )
            # Only include videos that actually exist on disk
            if os.path.exists(video_path):
                videos[qa['question']] = video_path

        # Also check for the idle nodding video
        idle_path = os.path.join(
            session_folder, "nodding_idle.mp4"
        )
        if os.path.exists(idle_path):
            videos['__idle__'] = idle_path

        # Store all this data back in memory for quick access
        _prep_sessions[session_id] = {
            'user_id': user_id,
            'meet_link': meet_link,
            'qa_list': qa_list,
            'videos': videos,
            'progress': 100,  # Already complete since we're reusing
            'status_messages': ['Session reloaded!'],
            'complete': True,
            'error': None,
            'session_folder': session_folder
        }
        print(f"[Join] Reloaded session {session_id} "
              f"with {len(videos)} videos")

    # Update the meeting link in the session (in case it changed)
    _prep_sessions[session_id]['meet_link'] = meet_link

    # Get the session data and videos
    sess = _prep_sessions[session_id]
    session_videos = sess.get('videos', {})

    print(f"[Join] Joining with {len(session_videos)} videos")

    # Save a new meeting record to the database
    # This tracks that the bot is now active in a meeting
    meeting = Meeting(
        user_id=user_id,
        meet_link=meet_link,
        meeting_context=sess.get('meeting_context', ''),
        session_id=session_id,
        status='active',
        started_at=datetime.utcnow()
    )
    db.session.add(meeting)
    db.session.commit()

    # Extract user values before the thread starts.
    user_context = user.context or ''
    user_photo_url = user.photo_url or ''
    user_id_val = user_id

    # Define a function to run the bot in the background
    # This way the API response is fast, but the bot starts joining
    def run_bot():
        # Use the app context because we're in a background thread
        with app.app_context():
            # Import the bot function
            from meet_bot import run_meet_bot
            # Start the bot with all the necessary information
            run_meet_bot(
                video_url='use_library',  # Use the videos from the session
                context=user_context,  # User's context/preferences
                image_url=user_photo_url,  # User's avatar image
                user_id=user_id_val,  # Who is running this
                meet_link=meet_link,  # Which meeting to join
                session_videos=session_videos  # The prepared videos to use
            )

    # Start the bot in a background thread so it doesn't block the response
    threading.Thread(target=run_bot, daemon=True).start()

    # Return success message to the frontend
    return jsonify({
        'message': 'Bot is joining the meeting!',
        'videos_loaded': len(session_videos)
    })

@app.route('/session-video/<user_id>/<session_id>/<filename>')
def serve_session_video(user_id, session_id, filename):
    """
    Serves session-specific video files.
    """
    import re
    from flask import send_from_directory
    
    # Security check
    safe_filename = re.sub(r'[^a-zA-Z0-9_\-\.]', '', filename)
    
    session_folder = os.path.join(
        os.getcwd(), "users", str(user_id), "sessions", str(session_id)
    )
    
    if not os.path.exists(os.path.join(session_folder, safe_filename)):
        return "Video not found", 404
        
    return send_from_directory(session_folder, safe_filename, mimetype='video/mp4')

@app.route('/api/sessions', methods=['POST'])
@require_firebase_auth
def create_session():
    user_id = flask_session.get('user_id')
    import uuid
    import json
    session_id = str(uuid.uuid4())[:8]
    
    session_folder = os.path.join(
        os.getcwd(), 'users', str(user_id),
        'sessions', session_id
    )
    os.makedirs(session_folder, exist_ok=True)
    
    meeting_session = MeetingSession(
        user_id=user_id,
        session_id=session_id,
        meeting_context="Empty Session",
        session_folder=session_folder,
        status='ready'
    )
    db.session.add(meeting_session)
    db.session.commit()
    
    s_dict = meeting_session.to_dict()
    s_dict['folder_exists'] = True
    s_dict['video_count_on_disk'] = 0
    return jsonify({'session': s_dict})

@app.route('/api/sessions', methods=['GET'])
@require_firebase_auth
def get_sessions():
    """
    Returns all past meeting preparation sessions
    for the current user. Videos are still available
    if the session folder exists on disk.
    """
    user_id = flask_session.get('user_id')

    sessions = MeetingSession.query.filter_by(
        user_id=user_id,
        status='ready'
    ).order_by(
        MeetingSession.created_at.desc()
    ).all()

    # Check which sessions still have videos on disk
    result = []
    for s in sessions:
        s_dict = s.to_dict()
        # Check if session folder still exists
        folder_exists = (
            s.session_folder and
            os.path.exists(s.session_folder)
        )
        # Count actual video files on disk
        video_count = 0
        if folder_exists:
            video_count = len([
                f for f in os.listdir(s.session_folder)
                if f.endswith('.mp4')
            ])
        s_dict['folder_exists'] = folder_exists
        s_dict['video_count_on_disk'] = video_count
        result.append(s_dict)

    return jsonify({'sessions': result})

@app.route('/api/sessions/<session_id>/reuse', methods=['POST'])
@require_firebase_auth
def reuse_session(session_id):
    """
    Allows user to reuse a past meeting session.
    Loads the session videos back into memory
    so the bot can join a new meeting with them.
    """
    global _prep_sessions
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)

    meeting_session = MeetingSession.query.filter_by(
        session_id=session_id,
        user_id=user_id
    ).first()

    if not meeting_session:
        return jsonify({'error': 'Session not found'}), 404

    if not os.path.exists(meeting_session.session_folder):
        return jsonify(
            {'error': 'Session videos no longer on disk'}
        ), 404

    import json

    # Reload session into memory
    qa_list = json.loads(meeting_session.qa_pairs or '[]')

    # Build videos dict from disk
    videos = {}
    session_folder = meeting_session.session_folder

    for i, qa in enumerate(qa_list):
        video_path = os.path.join(
            session_folder, f"q{i+1}.mp4"
        )
        if os.path.exists(video_path):
            videos[qa['question']] = video_path

    idle_path = os.path.join(
        session_folder, "nodding_idle.mp4"
    )
    if os.path.exists(idle_path):
        videos['__idle__'] = idle_path

    # Store in session (in-memory _prep_sessions)
    # This is for the status endpoint
    _prep_sessions[session_id] = {
        'user_id': user_id,
        'meet_link': user.meet_link or '',
        'qa_list': qa_list,
        'videos': videos,
        'progress': 100,
        'status_messages': ['Session reloaded!'],
        'complete': True,
        'error': None,
        'session_folder': session_folder
    }

    return jsonify({
        'session_id': session_id,
        'message': f'Session loaded with {len(videos)} videos!',
        'video_count': len(videos),
        'qa_count': len(qa_list)
    })

@app.route('/api/meetings/schedule', methods=['POST'])
@require_firebase_auth
def schedule_meeting():
    """
    Schedules a meeting for the bot to auto-join at a
    specific date and time.
    """
    user_id = flask_session.get('user_id')
    user = db.session.get(User, user_id)
    data = request.get_json()

    meet_link = data.get('meet_link')
    scheduled_date = data.get('scheduled_date')
    scheduled_time = data.get('scheduled_time')

    if not all([meet_link, scheduled_date, scheduled_time]):
        return jsonify({'error': 'All fields required'}), 400

    from datetime import datetime
    try:
        scheduled_dt = datetime.strptime(
            f"{scheduled_date} {scheduled_time}",
            "%Y-%m-%d %H:%M"
        )
    except ValueError:
        return jsonify({'error': 'Invalid date or time format'}), 400

    # Calculate seconds until meeting
    now = datetime.now()
    delay_seconds = (scheduled_dt - now).total_seconds()

    if delay_seconds < 0:
        return jsonify({'error': 'Meeting time is in the past'}), 400

    # Save to database
    meeting = Meeting(
        user_id=user_id,
        meet_link=meet_link,
        status='scheduled'
    )
    db.session.add(meeting)
    db.session.commit()

    # Extract user data before the background thread starts.
    user_context = user.context or ''
    user_photo_url = user.photo_url or ''
    user_id_val = user_id

    # Beginner-friendly comment: We start a "delayed join" process in the background.
    # It sleeps for the exact amount of time until the meeting starts.
    def delayed_join():
        import time
        print(f"[Scheduler] Waiting {delay_seconds:.0f}s until meeting...")
        time.sleep(delay_seconds)
        print(f"[Scheduler] Time to join meeting!")
        
        # Use app context because we are in a background thread
        with app.app_context():
            from meet_bot import run_meet_bot
            # Refresh meeting object from db
            meeting_obj = db.session.get(Meeting, meeting.id)
            if not meeting_obj:
                return
            
            meeting_obj.status = 'active'
            meeting_obj.started_at = datetime.now()
            db.session.commit()

            # Run the bot with the provided meeting details
            run_meet_bot(
                video_url='use_library', # Tells bot to use pre-generated library
                context=user_context,
                image_url=user_photo_url,
                user_id=user_id_val,
                meet_link=meet_link
            )

    thread = threading.Thread(
        target=delayed_join, daemon=True
    )
    thread.start()

    return jsonify({
        'message': f'Bot scheduled to join in {int(delay_seconds/60)} minutes!',
        'meeting_id': meeting.id
    })

@app.route('/api/meetings/<int:meeting_id>/summary',
           methods=['GET'])
@require_firebase_auth
def get_meeting_summary(meeting_id):
    """Returns the summary for a completed meeting."""
    user_id = flask_session.get('user_id')
    meeting = Meeting.query.filter_by(
        id=meeting_id, user_id=user_id
    ).first()

    if not meeting:
        return jsonify({'error': 'Meeting not found'}), 404

    return jsonify({
        'meeting': meeting.to_dict(),
        'summary': meeting.summary,
        'transcript': meeting.transcript
    })

@app.route('/api/meetings/<int:meeting_id>/generate-summary',
           methods=['POST'])
@require_firebase_auth
def generate_meeting_summary(meeting_id):
    """
    Generates a summary from the meeting transcript using OpenAI GPT-4o-mini.
    """
    user_id = flask_session.get('user_id')
    meeting = Meeting.query.filter_by(
        id=meeting_id, user_id=user_id
    ).first()

    if not meeting:
        return jsonify({'error': 'Meeting not found'}), 404

    try:
        from openai import OpenAI
        import os

        openai_client = OpenAI(
            api_key=os.getenv('OPENAI_API_KEY')
        )

        transcript = meeting.transcript or 'No transcript available'

        summary_response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{
                "role": "user",
                "content": f"""Summarize this meeting transcript
in a professional format with:
1. Key topics discussed
2. Questions asked
3. Main answers given
4. Action items if any

Transcript:
{transcript}"""
            }],
            max_tokens=500,
            temperature=0.7
        )

        summary = summary_response.choices[0].message.content
        meeting.summary = summary
        db.session.commit()

        return jsonify({
            'summary': summary,
            'transcript': transcript
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route("/api/meetings/<int:id>/stop", methods=["POST"])
@require_firebase_auth
def stop_meeting_api(id):
    """Stops an active meeting and saves the transcript."""
    user_id = flask_session.get("user_id")
    meeting = Meeting.query.filter_by(id=id, user_id=user_id).first()
    
    if meeting:
        # Save transcript before stopping
        try:
            from realtime_pipeline import get_meeting_transcript
            transcript = get_meeting_transcript()
            meeting.transcript = transcript
        except Exception as e:
            print(f"[StopMeeting] Failed to save transcript: {e}")

        meeting.status = "ended"
        meeting.ended_at = datetime.utcnow()
        db.session.commit()
        
    from realtime_listener import stop_listening
    stop_listening()
    
    import meet_bot
    if meet_bot._driver:
        try:
            meet_bot._driver.quit()
        except:
            pass
        meet_bot._driver = None
        
    return jsonify({"message": "Stopped", "meeting_id": id})

@app.route("/api/account", methods=["DELETE"])
@require_firebase_auth
def delete_account():
    """Deletes user account and data."""
    user_id = flask_session.get("user_id")
    user = db.session.get(User, user_id)
    db.session.delete(user)
    db.session.commit()
    flask_session.clear()
    return jsonify({"message": "Account deleted"})


@app.route('/api/debug/check-videos/<session_id>')
@require_firebase_auth
def check_session_videos(session_id):
    """
    Diagnostic route to check audio in session videos.
    Visit: /api/debug/check-videos/<session_id>
    """
    user_id = flask_session.get('user_id')

    meeting_session = db.session.query(MeetingSession).filter_by(
        session_id=session_id,
        user_id=user_id
    ).first()

    if not meeting_session:
        return jsonify({'error': 'Session not found'}), 404

    folder = meeting_session.session_folder
    if not os.path.exists(folder):
        return jsonify({'error': 'Folder not found'}), 404

    from video_utils import check_video_audio
    results = {}

    for filename in os.listdir(folder):
        if filename.endswith('.mp4'):
            path = os.path.join(folder, filename)
            results[filename] = check_video_audio(path)

    return jsonify({
        'session_id': session_id,
        'folder': folder,
        'videos': results
    })


if __name__ == '__main__':
    # Run the Flask development server on port 5000 with debug enabled
    app.run(debug=True, port=5000)
